import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    image: {
        width: "100%",
        aspectRatio: 8/7.5,
        resizeMode: 'cover',
    },
    flexRow: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    icon: {
        marginTop: 25,
        marginLeft: 25,
        color: "#B20530",
        position: 'absolute',
        zIndex: 1,
    },
    imageContainer: {
        position: 'relative', 
    },
    star: {
        color: '#B20530',
        position: 'absolute',
        zIndex: 1,
        marginTop: 25,
        marginLeft: 298,
    },
    cart: {
        color: '#B20530',
        position: 'absolute',
        zIndex: 1,
        marginTop: 25,
        marginLeft: 330,
    },
    name: {
        color: 'black',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 18,
        marginLeft: 25,
        marginTop: 10,
    },
    cookName: {
        color: 'gray',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 17,
        marginLeft: 25,
        marginTop: 5,
    },
    price: {
        color: 'black',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 16,
        marginLeft: 326,
        marginTop: -55,
    },
    flexContainer: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 20.5,
        marginLeft: 27,
        marginTop: 20,
    },
    flexColumn: {
        display: 'flex',
        flexDirection: 'column',
        borderRadius: 20,
        borderColor: '#B20530',
        borderWidth: 1,
        marginLeft: 27,
        marginTop: 20,
        marginRight: 30,
        marginBottom: 20,
    },
    text: {
        color: 'white',
        textAlign: 'center',
        marginTop: 10,
        marginBottom: 10,
        fontFamily: 'Inter_600SemiBold',
    },
    button: {
        backgroundColor: '#B20530',
        borderRadius: 30,
        width: 96,
        height: 60,
    },
    text1: {
        color: 'white',
        textAlign: 'center',
        marginTop: -6,
        fontSize: 12,
        fontFamily: 'Inter_400Regular',
    },
    text2: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 18,
        marginTop: 15,
        marginLeft: 25,
    },
    text3: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        marginTop: 5,
        marginLeft: 25,
        marginRight: 35,
    },
    ingredientList:{
        marginTop: 10,
    },
    ingredientContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 5,
        marginLeft: 27,
        marginRight: 30,
    },
    ingredientText: {
        fontSize: 14,
        fontFamily: 'Inter_400Regular',
    },
    controlsContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFD21C", 
        borderRadius: 20,
        paddingVertical: 5,
        paddingHorizontal: 10,
    },
    controlButton: {
        paddingHorizontal: 7,
    },
    controlText: {
        fontSize: 20,
        fontWeight: "bold",
        color: 'black',
    },
    quantity: {
        height: 30,
        width: 100,
        marginLeft: 255,
        marginTop: -25,
        paddingVertical: -10,
    },
    quantityText: {
        fontSize: 14,
        fontWeight: 'bold',
        marginHorizontal: 10,
        color: 'black',
    },
    comment: {
        backgroundColor: "#FFD21C",
        borderRadius: 20,
        marginTop: 15,
    },
    commentText: {
        fontSize: 14,
        color: 'gray',
        marginLeft: 10,
    },
    commentIcon: {
        marginRight: 20,
    },
    reviewName: {
        color: 'black',
        fontFamily: 'Inter_400Regular',
        fontSize: 15,
        marginLeft: 18,
        marginTop: 10,
        backgroundColor: '#fff',
    },
    reviewList: {
        borderWidth: 1,
        borderColor: "#B20530",
        borderRadius: 20,
        marginTop: 10,
        marginLeft: 27,
        marginRight: 30,
        marginBottom: 10,
        padding: 5, 
    },
    reviewText: {
        color: 'black',
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        marginLeft: 18,
        marginTop: 2,
        lineHeight: 20,
        marginBottom: 10,
        backgroundColor: '#fff',
    },
    reviewText2: {
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        marginLeft: 18,
        marginTop: 2,
        lineHeight: 20,
        backgroundColor: '#fff',
    },
    sendIcon: {
        marginRight: 7,
    },
    addReview: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 10,
        marginLeft: 10,
        marginRight: 10,
        paddingBottom: 10,
    },
    placeholder: {
        fontSize: 15,
        marginLeft: 5,
        paddingLeft: 7,
        color: 'gray',
    },
    rate:{
        marginTop: 10,
        marginLeft: 5,
    },
    reviewContainer: {
        marginBottom: 5,
        backgroundColor: '#fff',
    }
})